export default {
  order: {
    sortOrder: [
      "box",
      "grid",
      "flex",
      "margins",
      "borders",
      "sizing",
      "typography",
      "bg-visual",
      "transformations",
      "other",
    ],
  },
  categories: {
    box: [
      "block",
      "relative",
      "top",
      "right",
      "bottom",
      "left",
      "z-",
      "float",
      "clear",
      "box-border",
    ],
    grid: [
      "grid",
      "grid-cols",
      "grid-rows",
      "grid-flow-row",
      "grid-flow-col",
      "col-span-",
      "col-start-",
      "col-end-",
      "gap-",
      "row-span-",
      "row-start-",
      "row-end-",
      "auto-cols-",
      "auto-rows-",
      "auto-flow-",
      "grid-",
      "gap-",
    ],
    flex: [
      "flex",
      "flex-row",
      "flex-grow",
      "flex-shrink",
      "flex-basis",
      "justify-items-",
      "items-",
      "place-items-",
      "justify-",
      "content-",
      "place-content-",
      "order-",
    ],
    margins: [
      "m-",
      "mt-",
      "mr-",
      "mb-",
      "ml-",
      "p-",
      "pt-",
      "pr-",
      "pb-",
      "pl-",
    ],
    sizing: ["w-", "min-w-", "max-w-", "h-", "min-h-", "max-h-"],
    borders: [
      "border",
      "border-t",
      "border-r",
      "border-b",
      "border-l",
      "rounded",
      "rounded-tl",
      "rounded-tr",
      "rounded-bl",
      "rounded-br",
    ],
    typography: [
      "text-",
      "font-",
      "font-family",
      "text-",
      "font-style",
      "font-weight",
      "text-",
      "text-decoration",
      "uppercase",
      "text-indent",
      "leading-",
      "tracking-",
      "whitespace-",
    ],
    "bg-visual": [
      "bg-",
      "bg-opacity-",
      "bg-cover",
      "bg-contain",
      "bg-no-repeat",
      "bg-center",
      "bg-top",
      "bg-right",
      "bg-bottom",
      "bg-left",
      "opacity-",
      "shadow",
      "text-shadow",
      "backdrop-",
    ],
    transformations: [
      "transform",
      "origin-",
      "transition",
      "animate",
      "animate-",
      "duration-",
      "delay-",
      "ease-",
      "animate-repeat",
      "animate-direction",
      "animate-fill",
    ],
    other: [
      "cursor-",
      "invisible",
      "overflow-",
      "overflow-x-",
      "overflow-y-",
      "list-",
      "list-type-",
      "list-position-",
      "list-image-",
      "pointer-events-",
      "select-",
    ],
  },
};
